=== UO263595/sew_extraordinaria/peliculas.dtd
<!ELEMENT peliculas (pelicula+)>
<!ELEMENT pelicula (estreno, cines, descripcion, actores, bibliografia)>
<!ELEMENT estreno (#PCDATA)>
<!ELEMENT cines (cine+)>
<!ELEMENT cine (direccion, programacion)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT programacion (#PCDATA)>
<!ELEMENT descripcion (duracion, sinopsis, recomendacion)>
<!ELEMENT duracion (#PCDATA)>
<!ELEMENT sinopsis (#PCDATA)>
<!ELEMENT recomendacion (critica+)>
<!ELEMENT critica (#PCDATA)>
<!ELEMENT actores (actor+)>
<!ELEMENT actor (nacimiento, premios?, galeria)>
<!ELEMENT nacimiento (#PCDATA)>
<!ELEMENT premios (premio+)>
<!ELEMENT premio (#PCDATA)>
<!ELEMENT galeria (fotografia+, video*)>
<!ELEMENT fotografia (#PCDATA)>
<!ELEMENT video (#PCDATA)>
<!ELEMENT bibliografia (referencia+)>
<!ELEMENT referencia (#PCDATA)>

<!ATTLIST pelicula
	nombre CDATA #REQUIRED
	genero (Acción|Fantasía|Comedia|Drama|Suspense|Terror|Musical) #REQUIRED>
<!ATTLIST estreno
	fecha NMTOKEN #REQUIRED>
<!ATTLIST cine
	nombre CDATA #REQUIRED>
<!ATTLIST direccion
	ciudad CDATA #REQUIRED
	calle CDATA #REQUIRED>
<!ATTLIST programacion
	fecha NMTOKEN #REQUIRED
	hora NMTOKEN #REQUIRED>
<!ATTLIST duracion
	minutos NMTOKEN #REQUIRED>
<!ATTLIST recomendacion
	publico CDATA #REQUIRED
	puntuacion NMTOKEN #REQUIRED>
<!ATTLIST critica
	autor CDATA #REQUIRED>
<!ATTLIST actor
	nombre CDATA #REQUIRED
	apellidos CDATA #REQUIRED>
<!ATTLIST nacimiento
	fecha NMTOKEN #REQUIRED
	pais CDATA #REQUIRED>
<!ATTLIST premio
	fecha NMTOKEN #REQUIRED
	categoria CDATA #REQUIRED
	pelicula CDATA #IMPLIED
	resultado (Nominado|Nominada|Ganador|Ganadora) #REQUIRED>
<!ATTLIST fotografia
	enlace CDATA #REQUIRED>
<!ATTLIST video
	enlace CDATA #REQUIRED>
<!ATTLIST referencia
	enlace CDATA #REQUIRED>

=== UO263595/sew_extraordinaria/peliculas.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE peliculas SYSTEM "peliculas.dtd">

<peliculas
	xmlns="http://www.uniovi.es"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.uniovi.es peliculas.xsd">
	<pelicula nombre="Kill Bill" genero="Acción">
		<estreno fecha="2003-10-10"/>
		<cines>
			<cine nombre="Yelmo Cines">
				<direccion ciudad="Oviedo (Asturias)" calle="Calle Fernández Ladreda"/>
				<programacion fecha="2021-07-18" hora="16:00:00"/>
			</cine>
			<cine nombre="Cine Planelles">
				<direccion ciudad="Marchena (Sevilla)" calle="Calle Rojas Marcos"/>
				<programacion fecha="2021-07-16" hora="18:00:00"/>
			</cine>
			<cine nombre="Cines Van Golem Arlanzón">
				<direccion ciudad="Burgos (Cáceres)" calle="Avenida del Arlanzón"/>
				<programacion fecha="2021-07-28" hora="12:20:00"/>
			</cine>
		</cines>
		<descripcion>
			<duracion minutos="247"/>
			<sinopsis>
				Una mujer (Uma Thurman) despierta del coma cuatro años después de haber recibido una bala 
				en la cabeza durante el ensayo de su boda. Todos los asistentes murieron acribillados, 
				incluido el que iba a ser su marido. La matanza fue perpetrada por el Escuadrón Asesino Víbora Letal, 
				unos asesinos profesionales liderados por Bill (David Carradine). La mujer, conocida como La Novia, 
				pone en marcha su venganza contra Bill y todos sus secuaces.
			</sinopsis>
			<recomendacion publico="+18" puntuacion="8.7">
				<critica autor="Chicago Sun-Times">
					Quentin Tarantino muestra 'Kill Bill: Volumen 1' con poco esfuerzo y de manera brillante al mando de su técnica.
				</critica>
				<critica autor="The globe and mail">
					Es al mismo tiempo una espectacular realización y una película ligera.
				</critica>
				<critica autor="Rolling Stone">
					En 'Kill Bill', Tarantino lleva el delicioso pecado de regreso al cine; la emoción que se obtiene de algo, sucio y peligroso.
				</critica>
			</recomendacion>
		</descripcion>
		<actores>
			<actor nombre="Uma" apellidos="Thurman">
				<nacimiento fecha="2970-04-29" pais="Estados Unidos"/>
				<premios>
					<premio 
						fecha="1994" 
						categoria="Mejor Actriz de Reparto" 
						pelicula="Pulp Fiction"
						resultado="Nominada"
					/>
					<premio 
						fecha="2002" 
						categoria="Mejor actriz - Miniserie o telefilme" 
						pelicula="Ciegas de amor"
						resultado="Ganadora"
					/>
					<premio 
						fecha="2003" 
						categoria="Mejor actriz - Drama" 
						pelicula="Kill Bill"
						resultado="Nominada"
					/>
				</premios>
				<galeria>
					<fotografia enlace="https://westeurope1-mediap.svc.ms/transform/thumbnail?provider=spo&amp;inputFormat=jpg&amp;cs=fFNQTw&amp;docid=https%3A%2F%2Funioviedo-my.sharepoint.com%3A443%2F_api%2Fv2.0%2Fdrives%2Fb!XxbNJxMp30OOa--yyTva8BPAKFk7mH9Hm8nVMbjnwxuh0kMt0o5vTpgfp2kPpj2K%2Fitems%2F01MGZRGOGWJCTGIYPGRVBYANM2OZJB4QSN%3Fversion%3DPublished&amp;access_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIn0.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvdW5pb3ZpZWRvLW15LnNoYXJlcG9pbnQuY29tQDA1ZWE3NGEzLTkyYzUtNGMzMS05NzhhLTkyNWMzYzc5OWNkMCIsImlzcyI6IjAwMDAwMDAzLTAwMDAtMGZmMS1jZTAwLTAwMDAwMDAwMDAwMCIsIm5iZiI6IjE2MjQ1MTQ0MDAiLCJleHAiOiIxNjI0NTM2MDAwIiwiZW5kcG9pbnR1cmwiOiJzY1d1SmY0Q1Bxcm5FNHF4emdsVmRZd1dhQjJRUWFpcnVhbVAxQXE5eHFVPSIsImVuZHBvaW50dXJsTGVuZ3RoIjoiMTE5IiwiaXNsb29wYmFjayI6IlRydWUiLCJ2ZXIiOiJoYXNoZWRwcm9vZnRva2VuIiwic2l0ZWlkIjoiTWpkalpERTJOV1l0TWpreE15MDBNMlJtTFRobE5tSXRaV1ppTW1NNU0ySmtZV1l3IiwibmFtZWlkIjoiMCMuZnxtZW1iZXJzaGlwfHVvMjYzNTk1QHVuaW92aS5lcyIsIm5paSI6Im1pY3Jvc29mdC5zaGFyZXBvaW50IiwiaXN1c2VyIjoidHJ1ZSIsImNhY2hla2V5IjoiMGguZnxtZW1iZXJzaGlwfDEwMDNiZmZkYTMxZmMzYTNAbGl2ZS5jb20iLCJ0dCI6IjAiLCJ1c2VQZXJzaXN0ZW50Q29va2llIjoiMiJ9.NXpuZGJvbE1mQmxZNU4vNXU2WVZ5UXl1OCtjVGJ5WEQ2dWtveEZUa2NJND0&amp;encodeFailures=1&amp;width=1024&amp;height=630&amp;srcWidth=1024&amp;srcHeight=630"/>
					<fotografia enlace="https://westeurope1-mediap.svc.ms/transform/thumbnail?provider=spo&amp;inputFormat=jpg&amp;cs=fFNQTw&amp;docid=https%3A%2F%2Funioviedo-my.sharepoint.com%3A443%2F_api%2Fv2.0%2Fdrives%2Fb!XxbNJxMp30OOa--yyTva8BPAKFk7mH9Hm8nVMbjnwxuh0kMt0o5vTpgfp2kPpj2K%2Fitems%2F01MGZRGOFROYOCEE2HARELYV7U37F37I7M%3Fversion%3DPublished&amp;access_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIn0.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvdW5pb3ZpZWRvLW15LnNoYXJlcG9pbnQuY29tQDA1ZWE3NGEzLTkyYzUtNGMzMS05NzhhLTkyNWMzYzc5OWNkMCIsImlzcyI6IjAwMDAwMDAzLTAwMDAtMGZmMS1jZTAwLTAwMDAwMDAwMDAwMCIsIm5iZiI6IjE2MjQ1MTQ0MDAiLCJleHAiOiIxNjI0NTM2MDAwIiwiZW5kcG9pbnR1cmwiOiJzY1d1SmY0Q1Bxcm5FNHF4emdsVmRZd1dhQjJRUWFpcnVhbVAxQXE5eHFVPSIsImVuZHBvaW50dXJsTGVuZ3RoIjoiMTE5IiwiaXNsb29wYmFjayI6IlRydWUiLCJ2ZXIiOiJoYXNoZWRwcm9vZnRva2VuIiwic2l0ZWlkIjoiTWpkalpERTJOV1l0TWpreE15MDBNMlJtTFRobE5tSXRaV1ppTW1NNU0ySmtZV1l3IiwibmFtZWlkIjoiMCMuZnxtZW1iZXJzaGlwfHVvMjYzNTk1QHVuaW92aS5lcyIsIm5paSI6Im1pY3Jvc29mdC5zaGFyZXBvaW50IiwiaXN1c2VyIjoidHJ1ZSIsImNhY2hla2V5IjoiMGguZnxtZW1iZXJzaGlwfDEwMDNiZmZkYTMxZmMzYTNAbGl2ZS5jb20iLCJ0dCI6IjAiLCJ1c2VQZXJzaXN0ZW50Q29va2llIjoiMiJ9.NXpuZGJvbE1mQmxZNU4vNXU2WVZ5UXl1OCtjVGJ5WEQ2dWtveEZUa2NJND0&amp;encodeFailures=1&amp;width=958&amp;height=596&amp;srcWidth=958&amp;srcHeight=596"/>
					<fotografia enlace="https://westeurope1-mediap.svc.ms/transform/thumbnail?provider=spo&amp;inputFormat=jpg&amp;cs=fFNQTw&amp;docid=https%3A%2F%2Funioviedo-my.sharepoint.com%3A443%2F_api%2Fv2.0%2Fdrives%2Fb!XxbNJxMp30OOa--yyTva8BPAKFk7mH9Hm8nVMbjnwxuh0kMt0o5vTpgfp2kPpj2K%2Fitems%2F01MGZRGOH2DIJXM7GKNZFJK4JG7L2IYGJW%3Fversion%3DPublished&amp;access_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIn0.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvdW5pb3ZpZWRvLW15LnNoYXJlcG9pbnQuY29tQDA1ZWE3NGEzLTkyYzUtNGMzMS05NzhhLTkyNWMzYzc5OWNkMCIsImlzcyI6IjAwMDAwMDAzLTAwMDAtMGZmMS1jZTAwLTAwMDAwMDAwMDAwMCIsIm5iZiI6IjE2MjQ1MTQ0MDAiLCJleHAiOiIxNjI0NTM2MDAwIiwiZW5kcG9pbnR1cmwiOiJzY1d1SmY0Q1Bxcm5FNHF4emdsVmRZd1dhQjJRUWFpcnVhbVAxQXE5eHFVPSIsImVuZHBvaW50dXJsTGVuZ3RoIjoiMTE5IiwiaXNsb29wYmFjayI6IlRydWUiLCJ2ZXIiOiJoYXNoZWRwcm9vZnRva2VuIiwic2l0ZWlkIjoiTWpkalpERTJOV1l0TWpreE15MDBNMlJtTFRobE5tSXRaV1ppTW1NNU0ySmtZV1l3IiwibmFtZWlkIjoiMCMuZnxtZW1iZXJzaGlwfHVvMjYzNTk1QHVuaW92aS5lcyIsIm5paSI6Im1pY3Jvc29mdC5zaGFyZXBvaW50IiwiaXN1c2VyIjoidHJ1ZSIsImNhY2hla2V5IjoiMGguZnxtZW1iZXJzaGlwfDEwMDNiZmZkYTMxZmMzYTNAbGl2ZS5jb20iLCJ0dCI6IjAiLCJ1c2VQZXJzaXN0ZW50Q29va2llIjoiMiJ9.NXpuZGJvbE1mQmxZNU4vNXU2WVZ5UXl1OCtjVGJ5WEQ2dWtveEZUa2NJND0&amp;encodeFailures=1&amp;width=340&amp;height=420&amp;srcWidth=340&amp;srcHeight=420"/>
					<video enlace="https://unioviedo-my.sharepoint.com/:v:/g/personal/uo263595_uniovi_es/ETylKaiNEfpOplYtogMo_n0B7Ewvv4hyyZ_sFGT2Q6LXyA"/>
				</galeria>
			</actor>
			<actor nombre="David" apellidos="Carradine">
				<nacimiento fecha="1936-12-08" pais="Estados Unidos"/>
				<galeria>
					<fotografia enlace="https://westeurope1-mediap.svc.ms/transform/thumbnail?provider=spo&amp;inputFormat=jpg&amp;cs=fFNQTw&amp;docid=https%3A%2F%2Funioviedo-my.sharepoint.com%3A443%2F_api%2Fv2.0%2Fdrives%2Fb!XxbNJxMp30OOa--yyTva8BPAKFk7mH9Hm8nVMbjnwxuh0kMt0o5vTpgfp2kPpj2K%2Fitems%2F01MGZRGOABACKDXGV5WFF3RNORUMAHNGXV%3Fversion%3DPublished&amp;access_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIn0.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvdW5pb3ZpZWRvLW15LnNoYXJlcG9pbnQuY29tQDA1ZWE3NGEzLTkyYzUtNGMzMS05NzhhLTkyNWMzYzc5OWNkMCIsImlzcyI6IjAwMDAwMDAzLTAwMDAtMGZmMS1jZTAwLTAwMDAwMDAwMDAwMCIsIm5iZiI6IjE2MjQ1MTQ0MDAiLCJleHAiOiIxNjI0NTM2MDAwIiwiZW5kcG9pbnR1cmwiOiJzY1d1SmY0Q1Bxcm5FNHF4emdsVmRZd1dhQjJRUWFpcnVhbVAxQXE5eHFVPSIsImVuZHBvaW50dXJsTGVuZ3RoIjoiMTE5IiwiaXNsb29wYmFjayI6IlRydWUiLCJ2ZXIiOiJoYXNoZWRwcm9vZnRva2VuIiwic2l0ZWlkIjoiTWpkalpERTJOV1l0TWpreE15MDBNMlJtTFRobE5tSXRaV1ppTW1NNU0ySmtZV1l3IiwibmFtZWlkIjoiMCMuZnxtZW1iZXJzaGlwfHVvMjYzNTk1QHVuaW92aS5lcyIsIm5paSI6Im1pY3Jvc29mdC5zaGFyZXBvaW50IiwiaXN1c2VyIjoidHJ1ZSIsImNhY2hla2V5IjoiMGguZnxtZW1iZXJzaGlwfDEwMDNiZmZkYTMxZmMzYTNAbGl2ZS5jb20iLCJ0dCI6IjAiLCJ1c2VQZXJzaXN0ZW50Q29va2llIjoiMiJ9.NXpuZGJvbE1mQmxZNU4vNXU2WVZ5UXl1OCtjVGJ5WEQ2dWtveEZUa2NJND0&amp;encodeFailures=1&amp;width=275&amp;height=315&amp;srcWidth=275&amp;srcHeight=315"/>
					<fotografia enlace="https://westeurope1-mediap.svc.ms/transform/thumbnail?provider=spo&amp;inputFormat=jpg&amp;cs=fFNQTw&amp;docid=https%3A%2F%2Funioviedo-my.sharepoint.com%3A443%2F_api%2Fv2.0%2Fdrives%2Fb!XxbNJxMp30OOa--yyTva8BPAKFk7mH9Hm8nVMbjnwxuh0kMt0o5vTpgfp2kPpj2K%2Fitems%2F01MGZRGODDY7ZCV2T6INFY23RR2X5J2HLF%3Fversion%3DPublished&amp;access_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIn0.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvdW5pb3ZpZWRvLW15LnNoYXJlcG9pbnQuY29tQDA1ZWE3NGEzLTkyYzUtNGMzMS05NzhhLTkyNWMzYzc5OWNkMCIsImlzcyI6IjAwMDAwMDAzLTAwMDAtMGZmMS1jZTAwLTAwMDAwMDAwMDAwMCIsIm5iZiI6IjE2MjQ1MTQ0MDAiLCJleHAiOiIxNjI0NTM2MDAwIiwiZW5kcG9pbnR1cmwiOiJzY1d1SmY0Q1Bxcm5FNHF4emdsVmRZd1dhQjJRUWFpcnVhbVAxQXE5eHFVPSIsImVuZHBvaW50dXJsTGVuZ3RoIjoiMTE5IiwiaXNsb29wYmFjayI6IlRydWUiLCJ2ZXIiOiJoYXNoZWRwcm9vZnRva2VuIiwic2l0ZWlkIjoiTWpkalpERTJOV1l0TWpreE15MDBNMlJtTFRobE5tSXRaV1ppTW1NNU0ySmtZV1l3IiwibmFtZWlkIjoiMCMuZnxtZW1iZXJzaGlwfHVvMjYzNTk1QHVuaW92aS5lcyIsIm5paSI6Im1pY3Jvc29mdC5zaGFyZXBvaW50IiwiaXN1c2VyIjoidHJ1ZSIsImNhY2hla2V5IjoiMGguZnxtZW1iZXJzaGlwfDEwMDNiZmZkYTMxZmMzYTNAbGl2ZS5jb20iLCJ0dCI6IjAiLCJ1c2VQZXJzaXN0ZW50Q29va2llIjoiMiJ9.NXpuZGJvbE1mQmxZNU4vNXU2WVZ5UXl1OCtjVGJ5WEQ2dWtveEZUa2NJND0&amp;encodeFailures=1&amp;width=541&amp;height=815&amp;srcWidth=736&amp;srcHeight=1109"/>
					<video enlace="https://unioviedo-my.sharepoint.com/personal/uo263595_uniovi_es/_layouts/15/download.aspx?SourceUrl=%2Fpersonal%2Fuo263595_uniovi_es%2FDocuments%2Fmultimedia%2FDavid-Carradine%2Fvideo1.mp4&amp;correlationId=d1abfd58-4163-4ea2-a849-aecb06f5d668&amp;psi=47505438-20e9-4f4c-8222-6dd3a6368531&amp;ccat=2&amp;cs=fHxPbmVVcFdlYlBsYXllcg%3D%3D&amp;App=OneDriveWebVideo"/>
				</galeria>
			</actor>
			<actor nombre="Chiaki" apellidos="Kuriyama">
				<nacimiento fecha="2984-10-10" pais="Japón"/>
				<premios>
